//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16012775_CLDV_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUST()
        {
            this.INVOICEs = new HashSet<INVOICE>();
            this.JOBS = new HashSet<JOB>();
        }
    
        public string CUST_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_SURNAME { get; set; }
        public string CUST_ADDRESS { get; set; }
        public string CUST__PROVINCE { get; set; }
        public string CUST_ZIPCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBS { get; set; }
    }
}
