//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16012775_CLDV_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPS_JOBS
    {
        public string EMP_JOB_ID { get; set; }
        public Nullable<int> JOB_CARD_NO { get; set; }
        public string EMP_NO { get; set; }
    
        public virtual EMP EMP { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
