//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16012775_CLDV_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public string INVOICE_ID { get; set; }
        public int JOB_CARD_NO { get; set; }
        public string CUST_ID { get; set; }
        public int job_type_id { get; set; }
        public decimal invoice_amount { get; set; }
    
        public virtual CUST CUST { get; set; }
        public virtual JOB JOB { get; set; }
        public virtual JOB_TYPES JOB_TYPES { get; set; }
    }
}
