//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16012775_CLDV_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB()
        {
            this.EMPS_JOBS = new HashSet<EMPS_JOBS>();
            this.INVOICEs = new HashSet<INVOICE>();
            this.MATERIALS_PER_PROJECT = new HashSet<MATERIALS_PER_PROJECT>();
        }
    
        public int JOB_CARD_NO { get; set; }
        public Nullable<int> JOB_TYPE_ID { get; set; }
        public int NO_OF_DAYS { get; set; }
        public string CUST_ID { get; set; }
    
        public virtual CUST CUST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPS_JOBS> EMPS_JOBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual JOB_TYPES JOB_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALS_PER_PROJECT> MATERIALS_PER_PROJECT { get; set; }
    }
}
