//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16012775_CLDV_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALS_PER_PROJECT
    {
        public string MAT_PROJECT_ID { get; set; }
        public Nullable<int> JOB_CARD_NO { get; set; }
        public Nullable<int> MAT_ID { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual JOB JOB { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
