//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.JOBs = new HashSet<JOB>();
        }
    
        public string CUSTOMER_ID { get; set; }
        public string CUSTOMER_FISRT_NAME { get; set; }
        public string CUSTOMER_LAST_NAME { get; set; }
        public string CUSTOMER_STREET_ADDRESS { get; set; }
        public string CUSTOMER_CITY { get; set; }
        public string CUSTOMER_POSTAL_CODE { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBs { get; set; }
    }
}
