//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_JOB
    {
        public string EMP_JOB_ID { get; set; }
        public int JOB_CARD_NO { get; set; }
        public string EMP_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
