//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB_DETAILS()
        {
            this.JOBs = new HashSet<JOB>();
        }
    
        public string JOB_TYPE_ID { get; set; }
        public string JOB_TYPE_NAME { get; set; }
        public Nullable<decimal> DAILY_RATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBs { get; set; }
    }
}
