//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALS_JOB
    {
        public string MATERIAL_ID { get; set; }
        public int JOB_CARD_NO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual JOB JOB { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
